[
    uuid(EC3A7CE8-8F99-47ef-9705-DA5DF14F9A4C),
    version(1.0)
]

interface WechatSDK
{
    int Initialize();
    int AntiRevokeMsg();
    int UnAntiRevokeMsg();
    int StartSaveVoiceMsg([in, string]wchar_t* path);
    int StopSaveVoiceMsg();
    int SendTextMsg([in, string]wchar_t* wxid, [in, string]wchar_t* msg);
}